# Generated by Django 3.0.7 on 2020-06-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karma_web', '0019_auto_20200607_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ManyToManyField(to='karma_web.Customer'),
        ),
    ]
